# mysql-stack.yml

version: '3.7'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: foodzup
      MYSQL_USER: foodzup
      MYSQL_PASSWORD: foodzup
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - foodzup:/var/lib/mysql
    ports:
      - 3366:3306

  

  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8087:80

volumes:
  foodzup: