version: '3'
services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: foodzup
      MYSQL_USER: foodzup
      MYSQL_PASSWORD: foodzup
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - foodzup:/var/lib/mysql
    ports:
      - 3366:3306
    networks:
      service1_net:
        ipv4_address: 172.22.0.100
  
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: foodzup
      MONGO_INITDB_ROOT_PASSWORD: foodzup
    volumes:
      - foodzup2:/var/lib/mongodb
    networks:
      service1_net:
        ipv4_address: 172.22.0.101

volumes:
  foodzup:
  foodzup2:

networks:
  service1_net:
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/16
